// Copyright (C) 2014-2018 Ilya Chernetsov. All rights reserved. Contacts: <chernecoff@gmail.com>
// License: https://github.com/afrostalin/FireNET/blob/master/LICENSE

#pragma once

// Use default ip (127.0.0.1) - Only for testing on local machine
// Change it to 0 when update ssl certificate
#define USE_DEFAULT_IP 0

#if USE_DEFAULT_IP // Default ssl certificate (127.0.0.1)
#pragma message("WARNING : YOU USE DEFAULT SSL CERTIFICATE, CHANGE IT IN SSL_CERTIFICATE.h")
static const char* SSL_CERTIFICATE = "-----BEGIN CERTIFICATE-----\n"
"MIIC+TCCAmKgAwIBAgIJAKGNwM7z0k76MA0GCSqGSIb3DQEBCwUAMIGTMQswCQYD\n"
"VQQGEwJSVTEPMA0GA1UECAwGTW9zY293MQ4wDAYDVQQHDAVNb3NvdzERMA8GA1UE\n"
"CgwIQmlnQnJhaW4xETAPBgNVBAsMCEJpZ0JyYWluMRIwEAYDVQQDDAkxMjcuMC4w\n"
"LjExKTAnBgkqhkiG9w0BCQEWGmFmcm9zdGFsaW5Ac2FmZWd1YXJkcy5nYW1lMB4X\n"
"DTE3MTAxODE2MTE1N1oXDTE4MTAxODE2MTE1N1owgZMxCzAJBgNVBAYTAlJVMQ8w\n"
"DQYDVQQIDAZNb3Njb3cxDjAMBgNVBAcMBU1vc293MREwDwYDVQQKDAhCaWdCcmFp\n"
"bjERMA8GA1UECwwIQmlnQnJhaW4xEjAQBgNVBAMMCTEyNy4wLjAuMTEpMCcGCSqG\n"
"SIb3DQEJARYaYWZyb3N0YWxpbkBzYWZlZ3VhcmRzLmdhbWUwgZ8wDQYJKoZIhvcN\n"
"AQEBBQADgY0AMIGJAoGBAMIdStK1BGHgnGboayFjG8f+sQOxUSq+tOnVPkV8lDI8\n"
"oQMGeEjuedt0Q+vmn13o3Vle9VnjU+SWZgD9UDQ2uxMljgSjxCxqQ2hLvmDYEqaR\n"
"nDWGjoIQLt75cJNHHgBOI4rEQwFoPgSp5G6HWC49FR2PWncB5b748MhgUXRyHN6b\n"
"AgMBAAGjUzBRMB0GA1UdDgQWBBT8JCvx8Z+Dc8YJ1PogbVUpjQDyDzAfBgNVHSME\n"
"GDAWgBT8JCvx8Z+Dc8YJ1PogbVUpjQDyDzAPBgNVHRMBAf8EBTADAQH/MA0GCSqG\n"
"SIb3DQEBCwUAA4GBABVTO+vEjzfn8l+qxsmRC3I8g6R84TfJq7Q9bn1FRtM12EO3\n"
"7uGpVIyVATL7PVxLo6g0w0/NUKj9nO8vbb7d2KlUptug3d23qfqux2opu4/YVxhP\n"
"KfMItUqsEApdMxWJUsrJ3XpLi7DafxEL7rWc82o3SbV5UgpEfjfkVwwsZJyl\n"
"-----END CERTIFICATE-----\n";
#else // Setup you custom ssl certificate here
static const char* SSL_CERTIFICATE = "-----BEGIN CERTIFICATE-----\n"
"MIIC+TCCAmKgAwIBAgIJAKGNwM7z0k76MA0GCSqGSIb3DQEBCwUAMIGTMQswCQYD\n"
"VQQGEwJSVTEPMA0GA1UECAwGTW9zY293MQ4wDAYDVQQHDAVNb3NvdzERMA8GA1UE\n"
"CgwIQmlnQnJhaW4xETAPBgNVBAsMCEJpZ0JyYWluMRIwEAYDVQQDDAkxMjcuMC4w\n"
"LjExKTAnBgkqhkiG9w0BCQEWGmFmcm9zdGFsaW5Ac2FmZWd1YXJkcy5nYW1lMB4X\n"
"DTE3MTAxODE2MTE1N1oXDTE4MTAxODE2MTE1N1owgZMxCzAJBgNVBAYTAlJVMQ8w\n"
"DQYDVQQIDAZNb3Njb3cxDjAMBgNVBAcMBU1vc293MREwDwYDVQQKDAhCaWdCcmFp\n"
"bjERMA8GA1UECwwIQmlnQnJhaW4xEjAQBgNVBAMMCTEyNy4wLjAuMTEpMCcGCSqG\n"
"SIb3DQEJARYaYWZyb3N0YWxpbkBzYWZlZ3VhcmRzLmdhbWUwgZ8wDQYJKoZIhvcN\n"
"AQEBBQADgY0AMIGJAoGBAMIdStK1BGHgnGboayFjG8f+sQOxUSq+tOnVPkV8lDI8\n"
"oQMGeEjuedt0Q+vmn13o3Vle9VnjU+SWZgD9UDQ2uxMljgSjxCxqQ2hLvmDYEqaR\n"
"nDWGjoIQLt75cJNHHgBOI4rEQwFoPgSp5G6HWC49FR2PWncB5b748MhgUXRyHN6b\n"
"AgMBAAGjUzBRMB0GA1UdDgQWBBT8JCvx8Z+Dc8YJ1PogbVUpjQDyDzAfBgNVHSME\n"
"GDAWgBT8JCvx8Z+Dc8YJ1PogbVUpjQDyDzAPBgNVHRMBAf8EBTADAQH/MA0GCSqG\n"
"SIb3DQEBCwUAA4GBABVTO+vEjzfn8l+qxsmRC3I8g6R84TfJq7Q9bn1FRtM12EO3\n"
"7uGpVIyVATL7PVxLo6g0w0/NUKj9nO8vbb7d2KlUptug3d23qfqux2opu4/YVxhP\n"
"KfMItUqsEApdMxWJUsrJ3XpLi7DafxEL7rWc82o3SbV5UgpEfjfkVwwsZJyl\n"
"-----END CERTIFICATE-----\n";
#endif 